### ISSUE TITLE
Conflict with installing this composer package and the userforms

### ISSUE THREAD

**Issue by colinburns** [NobrainerWeb/Silverstripe-Content-Blocks#21]
Hi,

I was just trying to install this package today to give it a go and see how it works as this is a type of functionality I would really like to include in my sites... Unfortunately it looks as though there is a conflict in version for the gridfield extension. This package requires version 1.0.x I believe and the userforms module requires 1.1.x so I'm unable to install both at the same time... Though I would just mention this incase you missed it or you don't use userforms.

Thanks,
Colin

**Comment by sanderha** [comment]
Should be fixed now
