### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by enayet** [NobrainerWeb/Silverstripe-Content-Blocks#22]
Hi,

While trying to add a block getting the error

http://grab.by/LtvY

(top right corner)

Any idea.

Version: 3.2.0

Thank you.

**Comment by NobrainerWeb** [comment]
That error message is of no help - when the error show, try refreshing the page (CTRL + R).
If that does not give you a full error message, get SilverStripe into dev mode: 
https://docs.silverstripe.org/en/3.2/developer_guides/debugging/environment_types/

**Comment by enayet** [comment]
Thanks for the reply.

Dev mode is already enabled.

Solved the issue. The sortablefile dependent module was missing. I think it was not mentioned!

Thanks.

**Comment by enayet** [comment]
Got the solution from here:

https://www.versioneye.com/php/nobrainerweb:silverstripe-content-blocks/dev-master

Thanks.

**Comment by NobrainerWeb** [comment]
Glad you solved it :-)
