### ISSUE TITLE
Lock dependencies to minor versions rather than patch versions

### ISSUE THREAD

**Issue by dhensby** [NobrainerWeb/Silverstripe-Content-Blocks#27]
Related #21 

At the moment lots of your dependencies are locked to patch releases (`1.2.*`) rather than to minor releases (`1.*`)

[SemVer](http://semver.org/) says that these releases should not cause breaking changes and so it should be safe to lock to.

The current approach means that there can be incompatibility between modules or sites that have their own requirements.

**Comment by dhensby** [comment]
Note: You're requirements to CMS/Framework are as I'm suggesting, it's the other modules that should be too

**Comment by sanderha** [comment]
#31  should be fixed
