### ISSUE TITLE
Sort order is not unique across different pages

### ISSUE THREAD

**Issue by NobrainerWeb** [NobrainerWeb/Silverstripe-Content-Blocks#5]
GridFieldOrderableRows writes the sort order to all relations instead of just the currently active. A fix is to use SortableGridfield:
https://gist.github.com/NobrainerWeb/9205539

https://github.com/UndefinedOffset/SortableGridField/blob/master/docs/ManyManyExample.md

**Comment by sanderha** [comment]
Seems to have been fixed somewhere down the line in ContentBlocksModule.php 
```php
	private static $many_many_extraFields = array(
        'Blocks' => array(
			'SortOrder'=>'Int'
		)
    );
```
